-- Reason: organize upstreams and model monitors with user-managed tags.
-- Scope: additive management metadata; routing, credentials and probe history are unchanged.

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT 'gray',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_name_ci ON tags (LOWER(name));

CREATE TABLE IF NOT EXISTS upstream_tags (
    upstream_id BIGINT NOT NULL REFERENCES upstreams(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (upstream_id, tag_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_upstream_primary_tag
    ON upstream_tags(upstream_id) WHERE is_primary=TRUE;
CREATE INDEX IF NOT EXISTS idx_upstream_tags_tag
    ON upstream_tags(tag_id, upstream_id);

INSERT INTO tags(name, color, sort_order)
SELECT DISTINCT BTRIM(source), 'gray', 0
FROM upstreams
WHERE BTRIM(source) <> ''
ON CONFLICT DO NOTHING;

INSERT INTO upstream_tags(upstream_id, tag_id, is_primary)
SELECT u.id, t.id, TRUE
FROM upstreams u
JOIN tags t ON LOWER(t.name)=LOWER(BTRIM(u.source))
WHERE BTRIM(u.source) <> ''
ON CONFLICT (upstream_id, tag_id) DO UPDATE SET is_primary=TRUE;
