-- Reason: persist intelligent-routing decisions, cache observations, and model mappings.
-- Scope: additive schema only; existing request and billing data is unchanged.

ALTER TABLE upstreams
    ADD COLUMN IF NOT EXISTS cache_mode TEXT NOT NULL DEFAULT 'auto';

ALTER TABLE request_attempts
    ADD COLUMN IF NOT EXISTS mapped_model TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS route_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL UNIQUE,
    group_id BIGINT NOT NULL DEFAULT 0,
    model TEXT NOT NULL DEFAULT '',
    protocol TEXT NOT NULL DEFAULT '',
    endpoint TEXT NOT NULL DEFAULT '',
    session_key TEXT NOT NULL DEFAULT '',
    prefix_hash TEXT NOT NULL DEFAULT '',
    cache_key TEXT NOT NULL DEFAULT '',
    strategy TEXT NOT NULL DEFAULT 'cost',
    reason TEXT NOT NULL DEFAULT '',
    selected_upstream_id BIGINT NOT NULL DEFAULT 0,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    forecast_window_seconds BIGINT NOT NULL DEFAULT 0,
    forecast_requests DOUBLE PRECISION NOT NULL DEFAULT 0,
    estimated_input_tokens BIGINT NOT NULL DEFAULT 0,
    reusable_prefix_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_output_tokens BIGINT NOT NULL DEFAULT 0,
    selected_cost DOUBLE PRECISION,
    no_cache_cost DOUBLE PRECISION,
    cache_cost DOUBLE PRECISION,
    estimated_savings DOUBLE PRECISION,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    cache_selected BOOLEAN NOT NULL DEFAULT FALSE,
    exploration BOOLEAN NOT NULL DEFAULT FALSE,
    actual_cost DOUBLE PRECISION,
    actual_input_tokens BIGINT,
    actual_output_tokens BIGINT,
    actual_cached_tokens BIGINT,
    actual_cache_creation_tokens BIGINT,
    actual_outcome TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS route_decision_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id BIGINT NOT NULL REFERENCES route_decisions(id) ON DELETE CASCADE,
    upstream_id BIGINT NOT NULL DEFAULT 0,
    api_key_hash TEXT NOT NULL DEFAULT '',
    upstream_name TEXT NOT NULL DEFAULT '',
    protocol TEXT NOT NULL DEFAULT '',
    priority INTEGER NOT NULL DEFAULT 0,
    eligible BOOLEAN NOT NULL DEFAULT TRUE,
    selected BOOLEAN NOT NULL DEFAULT FALSE,
    rejection_reason TEXT NOT NULL DEFAULT '',
    pricing_source TEXT NOT NULL DEFAULT '',
    pricing_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    cache_supported BOOLEAN NOT NULL DEFAULT FALSE,
    cache_existing BOOLEAN NOT NULL DEFAULT FALSE,
    cache_selected BOOLEAN NOT NULL DEFAULT FALSE,
    cache_hit_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    forecast_total_cost DOUBLE PRECISION,
    forecast_no_cache_cost DOUBLE PRECISION,
    forecast_cache_cost DOUBLE PRECISION,
    estimated_savings DOUBLE PRECISION,
    break_even_requests DOUBLE PRECISION,
    expected_hits DOUBLE PRECISION NOT NULL DEFAULT 0,
    expected_misses DOUBLE PRECISION NOT NULL DEFAULT 0,
    expected_creates DOUBLE PRECISION NOT NULL DEFAULT 0,
    estimated_ttft_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
    estimated_duration_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
    success_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    details_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS routing_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL,
    attempt_no INTEGER NOT NULL DEFAULT 1,
    group_id BIGINT NOT NULL DEFAULT 0,
    upstream_id BIGINT NOT NULL DEFAULT 0,
    api_key_hash TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    session_key TEXT NOT NULL DEFAULT '',
    prefix_hash TEXT NOT NULL DEFAULT '',
    cache_key TEXT NOT NULL DEFAULT '',
    prefix_tokens BIGINT NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    cached_tokens BIGINT NOT NULL DEFAULT 0,
    cache_creation_tokens BIGINT NOT NULL DEFAULT 0,
    ttft_ms BIGINT NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    cache_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    cache_created BOOLEAN NOT NULL DEFAULT FALSE,
    cache_expires_at TIMESTAMPTZ,
    observed_at TIMESTAMPTZ NOT NULL,
    UNIQUE (request_id, attempt_no)
);

CREATE TABLE IF NOT EXISTS upstream_prefix_cache_stats (
    api_key_hash TEXT NOT NULL,
    upstream_id BIGINT NOT NULL,
    model TEXT NOT NULL,
    prefix_hash TEXT NOT NULL,
    session_key TEXT NOT NULL DEFAULT '',
    cache_key TEXT NOT NULL DEFAULT '',
    prefix_tokens BIGINT NOT NULL DEFAULT 0,
    observations BIGINT NOT NULL DEFAULT 0,
    hit_count BIGINT NOT NULL DEFAULT 0,
    miss_count BIGINT NOT NULL DEFAULT 0,
    create_count BIGINT NOT NULL DEFAULT 0,
    last_hit_at TIMESTAMPTZ,
    last_miss_at TIMESTAMPTZ,
    last_created_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (api_key_hash, upstream_id, model, prefix_hash)
);

CREATE TABLE IF NOT EXISTS model_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upstream_id BIGINT NOT NULL DEFAULT 0,
    source_model TEXT NOT NULL,
    target_model TEXT NOT NULL,
    mapping_type TEXT NOT NULL DEFAULT 'static',
    failure_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (upstream_id, source_model)
);

CREATE TABLE IF NOT EXISTS upstream_models (
    upstream_id BIGINT NOT NULL REFERENCES upstreams(id) ON DELETE CASCADE,
    model TEXT NOT NULL,
    updated_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (upstream_id, model)
);

CREATE INDEX IF NOT EXISTS idx_route_decisions_created
    ON route_decisions(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_route_decisions_session_model
    ON route_decisions(session_key, model, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_route_decisions_prefix_model
    ON route_decisions(prefix_hash, model, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_route_candidates_decision
    ON route_decision_candidates(decision_id);
CREATE INDEX IF NOT EXISTS idx_route_candidates_upstream
    ON route_decision_candidates(upstream_id, decision_id DESC);
CREATE INDEX IF NOT EXISTS idx_routing_observations_time
    ON routing_observations(observed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_routing_observations_session_model
    ON routing_observations(session_key, model, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_routing_observations_prefix_model
    ON routing_observations(prefix_hash, model, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_routing_observations_upstream_model
    ON routing_observations(upstream_id, model, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_upstream_prefix_cache_expiry
    ON upstream_prefix_cache_stats(api_key_hash, upstream_id, model, expires_at);
CREATE INDEX IF NOT EXISTS idx_model_mappings_source
    ON model_mappings(source_model);
CREATE INDEX IF NOT EXISTS idx_model_mappings_upstream
    ON model_mappings(upstream_id, source_model);

INSERT INTO settings(key, value)
VALUES ('billing_snapshot_retention_days', '0')
ON CONFLICT(key) DO NOTHING;

INSERT INTO settings(key, value)
VALUES ('probe_retention_hours', '0')
ON CONFLICT(key) DO NOTHING;
