CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS upstreams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    base_url TEXT NOT NULL,
    api_key TEXT NOT NULL,
    proxy TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    channel_probe BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS group_upstreams (
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    upstream_id BIGINT NOT NULL REFERENCES upstreams(id) ON DELETE CASCADE,
    priority INTEGER NOT NULL DEFAULT 50,
    weight INTEGER NOT NULL DEFAULT 1,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (group_id, upstream_id)
);

CREATE TABLE IF NOT EXISTS access_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    key TEXT NOT NULL UNIQUE,
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS monitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upstream_id BIGINT NOT NULL REFERENCES upstreams(id) ON DELETE CASCADE,
    model TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    stream BOOLEAN NOT NULL DEFAULT FALSE,
    probe_text TEXT NOT NULL DEFAULT '',
    max_tokens INTEGER NOT NULL DEFAULT 0,
    interval_sec INTEGER NOT NULL DEFAULT 0,
    path TEXT NOT NULL DEFAULT '',
    sort INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS probe_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id BIGINT NOT NULL REFERENCES monitors(id) ON DELETE CASCADE,
    status INTEGER NOT NULL,
    latency_ms BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL UNIQUE,
    group_id BIGINT NOT NULL DEFAULT 0,
    final_upstream_id BIGINT NOT NULL DEFAULT 0,
    model TEXT NOT NULL DEFAULT '',
    endpoint TEXT NOT NULL DEFAULT '',
    key_name TEXT NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 0,
    outcome TEXT NOT NULL,
    ttft_ms BIGINT NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    error_text TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS request_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL REFERENCES requests(request_id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL,
    upstream_id BIGINT NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 0,
    outcome TEXT NOT NULL,
    ttft_ms BIGINT NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    error_text TEXT NOT NULL DEFAULT '',
    UNIQUE (request_id, attempt_no)
);

CREATE INDEX IF NOT EXISTS idx_probe_results_monitor_time
    ON probe_results(monitor_id, created_at);
CREATE INDEX IF NOT EXISTS idx_requests_created_at
    ON requests(created_at);
CREATE INDEX IF NOT EXISTS idx_requests_group_time
    ON requests(group_id, created_at);
CREATE INDEX IF NOT EXISTS idx_requests_model_time
    ON requests(model, created_at);
CREATE INDEX IF NOT EXISTS idx_requests_outcome_time
    ON requests(outcome, created_at);
CREATE INDEX IF NOT EXISTS idx_attempts_request
    ON request_attempts(request_id, attempt_no);
CREATE INDEX IF NOT EXISTS idx_attempts_upstream_time
    ON request_attempts(upstream_id, created_at);
