-- Add provider billing metadata and snapshots for balance, multiplier, and cost auditing.
-- Affects upstream configuration and creates independent runtime/history tables.
ALTER TABLE upstreams
    ADD COLUMN billing_type TEXT NOT NULL DEFAULT 'none';

CREATE TABLE upstream_billing_status (
    upstream_id BIGINT PRIMARY KEY REFERENCES upstreams(id) ON DELETE CASCADE,
    currency TEXT NOT NULL DEFAULT 'USD',
    remaining DOUBLE PRECISION,
    unlimited BOOLEAN NOT NULL DEFAULT FALSE,
    billing_group TEXT NOT NULL DEFAULT '',
    group_multiplier DOUBLE PRECISION,
    effective_multiplier DOUBLE PRECISION,
    reported_list_cost DOUBLE PRECISION,
    reported_actual_cost DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'pending',
    error_text TEXT NOT NULL DEFAULT '',
    observed_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE upstream_billing_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upstream_id BIGINT NOT NULL REFERENCES upstreams(id) ON DELETE CASCADE,
    currency TEXT NOT NULL DEFAULT 'USD',
    remaining DOUBLE PRECISION,
    unlimited BOOLEAN NOT NULL DEFAULT FALSE,
    billing_group TEXT NOT NULL DEFAULT '',
    group_multiplier DOUBLE PRECISION,
    effective_multiplier DOUBLE PRECISION,
    reported_list_cost DOUBLE PRECISION,
    reported_actual_cost DOUBLE PRECISION,
    observed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_upstream_billing_snapshots_time
    ON upstream_billing_snapshots(upstream_id, observed_at DESC);
